import type { Metadata } from "next";
import "./(app)/styles/globals.css";
import "./(app)/styles/tailwind.css";
import { AppProvider } from "./(app)/providers";
import { Toast } from "@/shared/ui/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AppProvider>{children}</AppProvider>
        <Toast position="top-right" />
      </body>
    </html>
  );
}
