import type { Metadata } from "next";
import "./(app)/styles/globals.css";
import "./(app)/styles/tailwind.css";
import { fontClasses } from "@/shared/fonts";
import { AppProvider } from "./(app)/providers";
import { Toast } from "@/shared/ui/toast";
import { Navigation } from "@/widgets/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${fontClasses}`}>
      <body>
        <AppProvider>
          <Navigation />
          {children}
        </AppProvider>
        <Toast position="top-right" />
      </body>
    </html>
  );
}
